# remap prefix to backtick
# and backtick twice jumps to the previous window
unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix
# reload ~/.tmux.conf using PREFIX r
bind r source-file ~/.tmux.conf \; display 'sourcing ~/.tmux.conf --wait a sec--'

# create a command to run the sessionizer script
bind-key -r f run-shell "tmux neww ~/tmux_sessionizer.sh"
# NOTE: can call with dir after it like so: "tmux neww ~/tmux-sessionizer.sh my_dir"
# if no dir is given, then it will fzf in the dirs listed in tmux_sessionizer.sh

# geohot 'tmux conf for pi'
set -g extended-keys on
set -g extended-keys-format csi-u

setw -g aggressive-resize on
set -g history-limit 50000

# use zsh regardless of default settings
set -g default-shell /opt/homebrew/bin/zsh
if-shell 'test -x /opt/homebrew/bin/zsh' 'set-option -g default-shell /opt/homebrew/bin/zsh'

# use vim shortcuts (emacs is default) for help and copy modes
setw -g mode-keys vi
# emacs key bindings in tmux command prompt (prefix + :) are better than vi keys, even for vim users
set -g status-keys emacs

# disable scroll in buffers
set -g mouse off
# enable focus events (for terminals that support them)
set -g focus-events on
# solve the usual OSX/macOS issue
set -g default-command "reattach-to-user-namespace -l $SHELL"
# display messages for 4 seconds
set -g display-time 2000
# allow for faster key repetition
set -s escape-time 0
# Esc and Alt are encoded similarly in a terminal (e.g. Esc-x = Alt-x)
# so when hitting Esc in vi mode, the terminal will wait
# setting the 'escape-time' delay to 0 makes a standalone Esc register immediately

# necessary to have vim theme/powerline properly formatted
set -g default-terminal "screen-256color"
# enable italics (relevant especially in Vim)
# the following is mega-danger: https://unix.stackexchange.com/a/1098
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# # align tab name with tmux session name
# set-option -g set-titles on
# # set-option -g set-titles-string "#{session_name} - #{host}" # keep for legacy purposes
# set-option -g set-titles-string "TMUX::#{session_name}"


set -g status on
set -g status-position bottom
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 50
# message text
set -g message-style fg=black,bg=green
# set update frequency (default: 15 seconds)
set -g status-interval 1

# default window title colors
setw -g window-status-style fg=white,bg=default,dim
setw -g window-status-format " #I: #W "
# focused window title colors
setw -g window-status-current-style fg=blue,bg=default #,bright <= changes width
setw -g window-status-current-format " #[fg=white]#I#[fg=default]:#[bg=black] #W#F"
# pane border
set -g pane-border-style fg=black,bg=default
set -g pane-active-border-style fg=black,bg=default

# set statusbar content
set -g status-left '#[fg=grey][#[reverse] TMUX #[noreverse] #[fg=green,bright]@#S#[fg=grey,nobright]]'
set -g status-right "#[fg=yellow]#{?client_prefix,#[reverse] PREFIX #[noreverse] ,#[dim] PREFIX #[nodim] } #[fg=grey]%a %Y-%m-%d #[fg=red][%H:%M:%S]"
